# Develop override settings

url: http://localhost:4000

analytics:
  provider: "google-universal"
  google:
    tracking_id: "UA-1234567-8"

comments:
  disqus:
    shortname            : "mmistakes-dev"

sass:
  style: expanded
